@startuml

class AccountController {
    + Register(username: string, email: string, password: string)
    + Login(username: string, password: string)
    + AddChild(childId: Guid)
    + Update(newPassword: string, newPhoneNumber: string)
    + GetLoggedUser()
    + GetUserById(userId: string)
}

class AccountService {
    + Register(username: string, email: string, password: string)
    + Login(username: string, password: string)
    + AddChild(childId: Guid)
    + Update(newPassword: string, newPhoneNumber: string)
    + GetLoggedUser()
    + GetUserById(userId: string)
}

interface IAccountService {
    + Register()
    + Login()
    + AddChild()
    + Update()
    + GetLoggedUser()
    + GetUserById()
}

class SchoolController {
    + GetAllSchools()
    + Create(requestModel: SchoolCreateRequest)
    + Update(requestModel: SchoolUpdateRequest)
    + Delete(name: string)
    - ValidateRequest()
    - ExtractSchool(SchoolCreateRequest requestModel)
    - GetLoggedUser()
    - IsAdmin(AspNetUser user)
}

class SchoolService {
    + GetAllSchools()
    + Create(newSchool: School)
    + Update(updatedSchool: School)
    + Delete(schoolName: string)
}

interface ISchoolService {
    + GetAllSchools()
    + Create()
    + Update()
    + Delete()
}

class CurricullumController {
    + Create(requestModel: CurricullumCreateRequest)
    + Update(requestModel: CurricullumUpdateRequest)
    + Delete(id: Guid)
    + GetBySchoolClass(schoolClassId: Guid)
}

class CurricullumService {
    + Create(newCurriculum: Curricullum)
    + Update(updatedCurriculum: Curricullum)
    + Delete(curriculumId: Guid)
    + GetBySchoolClass(schoolClassId: Guid)
}

interface ICurricullumService {
    + Create()
    + Update()
    + Delete()
    + GetBySchoolClass()
}

database GradeCenterContext

AccountController ...> IAccountService : uses
SchoolController ...> ISchoolService : uses
CurricullumController ...> ICurricullumService : uses
CurricullumController ...> ISchoolService : uses

ISchoolService <|.. SchoolService : implements
IAccountService <|.. AccountService : implements
ICurricullumService <|.. CurricullumService : implements

SchoolService --> GradeCenterContext
AccountService --> GradeCenterContext
CurricullumService --> GradeCenterContext

@enduml
